config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticated :user do
    root :to => "patients#index", as: :all_patients
  end

  root :to => 'welcome#index'

  resources :patients do
    collection do
      get :autocomplete
    end
    resources :visits do
      resources :prescription
    end
  end
end

app/models/patient.rb
class Patient < ActiveRecord::Base
	has_many :visits

	searchkick autocomplete: ['name']

	def age
	  now = Time.now.utc.to_date
	  now.year - self.DOB.year - ((now.month > self.DOB.month || (now.month == self.DOB.month && now.day >= self.DOB.day)) ? 0 : 1)
	end
end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
  belongs_to :visit
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :patient
  has_many :prescriptions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

	before_action :authenticate_user!

	def new
		@patient = Patient.new 
	end

	def create
		@patient = Patient.new(patient_params)
		if @patient.save
      		flash[:info] = "Patient has been saved"
      		redirect_to @patient
      	else
      		render 'new'
		end
	end

	def show
		@patient = Patient.find(params[:id])
		@visits = @patient.visits.paginate(:page => params[:page])
	end

	def index
		if params[:query].present?
      		@patients = Patient.search(params[:query], page: params[:page])
    	else
      		@patients = Patient.paginate(page: params[:page])
    	end
	end

	def edit
		@patient = Patient.find(params[:id])
	end

	def update
	    @patient = Patient.find(params[:id])
	    if @patient.update(patient_params)
	      flash[:success] = "Patient updated"
	      redirect_to @patient
	    else
	      render 'edit'
	    end
  	end

  def destroy
	@patient = Patient.find(params[:id])
	if  @patient.destroy
	  flash[:alert] = "Patient deleted"
	end
	 
	redirect_to patients_path
  end

  def autocomplete
    render json: Patient.search(params[:query], autocomplete: true, limit: 10).map(&:name)
  end

	private
	def patient_params
		params.require(:patient).permit(:name, :gender, :DOB)
	end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_patient
  before_action :set_visit, only: [:edit, :show, :update, :destroy]
  
  def new
    @visit = @patient.visits.build 
  end

  def create
    visit = @patient.visits.create(visit_params)
    if visit
          flash[:info] = "Visit date has been fixed"
          redirect_to patient_visit_path(@patient, visit)
        else
          render 'new'
    end
  end

  def update
      if @visit.update(visit_params)
        flash[:success] = "visit date has been updated"
        redirect_to patient_visit_path(@patient, @visit)
      else
        render 'edit'
      end
  end

  def edit
  end

  def destroy
    @visit.destroy
    flash[:alert] = "Vist has been canceled"
     
    redirect_to patient_visits_path(@patient)
  end

  def show
  end

  private
    def set_patient
      @patient = Patient.find(params[:patient_id])
    end

    def set_visit
      @visit = @patient.visits.find(params[:id])
    end

  def visit_params
    params.require(:visit).permit(:next)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
    	base_title = "Bilal Hospital"
    	if page_title.empty?
      		base_title
    	else
      		"#{page_title} | #{base_title}"
    	end
  	end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Bilal Hospital", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", '#' %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Patients", patients_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", '#' %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
            <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.9.3/typeahead.min.js"%>
    <%= stylesheet_link_tag 'application', media: 'all',
                            'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/patients/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@patient) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', required: true %>

        <%= f.label :gender %>
        <%= f.select(:gender, options_for_select([['Male','Male'], ['Female','Female']])) %>

        <%= f.label 'Date of birth' %>
        <%= f.date_field :DOB, class: 'form-control', required: true %>

        <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/patients/edit.html.erb
<% provide(:title, 'Edit Patient') %>
<h1> Edit Patient </h1>

<%= render 'form' %>

app/views/patients/index.html.erb
<% provide(:title, 'All Patients') %>

<div>
    <p> <%= link_to  new_patient_path, class: "btn btn-success" do  %>
            <i class="glyphicon glyphicon-plus"> Add new patient</i>
        <%end%>
    </p>
</div>

<h1>Patients</h1>

<% if false %>
<%= form_tag patients_path, class: "form-inline", method: :get do %>
  <div class="row">
    <div class="input-group">
      <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "search. . .", id: "patient_search", autocomplete: "off" %>
      <span class="input-group-btn">
        <%= submit_tag "Search", class: "btn btn-primary" %>
      </span>
    </div>
  </div>    
  <% if params[:query].present? %>
    <%= link_to "clear", patients_path %>
  <% end %>
<% end %>
<%end%>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="row">
    	<div class="col-md-2">
    	  <h2> Name </h2>
    	</div>
    	<div class="col-md-2">
    	  <h2> Gender </h2>
    	</div>
    	<div class="col-md-2">
    	  <h2> Date of Birth </h2>
    	</div>
    	<div class="col-md-2">
    	  <h2> View </h2>
    	</div>
        <div class="col-md-2">
          <h2> Edit </h2>
        </div>
        <div class="col-md-2">
          <h2> Delete </h2>
        </div>
    </div>
    <% @patients.each do |patient| %>
	  <div class="row">
    	<div class="col-md-2">
    	  <p class="text-center"> <%= patient.name %> </p>
    	</div>
    	<div class="col-md-2">
    	  <p class="text-center"> <%= patient.gender %> </p>
    	</div>
    	<div class="col-md-2">
          <%if patient.DOB %>
    	    <p class="text-center"> <%= patient.DOB.to_formatted_s(:rfc822) %> </p>
    	   <% end %>
        </div>
    	<div class="col-md-2">
    	  <p> <%= link_to 'show', patient_path(patient), class: "center-block btn btn-primary" %> </p>
    	</div>
        <div class="col-md-2">
          <p> <%= link_to 'edit', edit_patient_path(patient), class: "center-block btn btn-info" %> </p>
        </div>
        <div class="col-md-2">
          <p> <%= link_to 'delete', patient_path(patient), 
            method: :delete,
            data: { confirm: 'Are you sure?' },
            class: "center-block btn btn-danger" %> 
          </p>
        </div>
      </div>
    <% end %>
    <%= will_paginate @patients %>
  </div>
</div>

app/views/patients/new.html.erb
<% provide(:title, 'Add Patient') %>
<h2>Add patient information here</h2>

<%= render 'form' %>

app/views/patients/show.html.erb
<% provide(:title, 'Patient') %>

<h1> <%= @patient.name %> </h1>

<div class="row">
  <div class="col-sm-9 col-md-offset-3">
    <div class="row">
      <div class="col-xs-8 col-sm-6">
        Gender:
      </div>
      <div class="col-xs-4 col-sm-6">
        <%= @patient.gender %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-8 col-sm-6">
        Date of birth:
      </div>
      <div class="col-xs-4 col-sm-6">
      	<% if @patient.DOB %>
        	<%= @patient.DOB.to_formatted_s(:long)%>
        <% end %>	
      </div>
    </div>
    <div class="row">
      <div class="col-xs-8 col-sm-6">
        Age:
      </div>
      <div class="col-xs-4 col-sm-6">
      	<% if @patient.DOB %>
        	<%= @patient.age %> years
        <% end %>	
      </div>
    </div>
  </div>
</div>

<div>
    <p> <%= link_to  new_patient_visit_path(@patient), class: "btn btn-success" do  %>
            <i class="glyphicon glyphicon-plus"> Fix an Appointment</i>
        <%end%>
    </p>
</div>



<h1>Appointments</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="row">
      <div class="col-md-3">
        <h2> Date </h2>
      </div>
      <div class="col-md-3">
        <h2> Prescriptions </h2>
      </div>
        <div class="col-md-3">
          <h2> Change Appointment </h2>
        </div>
        <div class="col-md-3">
          <h2> Delete Appointment </h2>
        </div>
    </div>
    <% @visits.each do |visit| %>
    <div class="row">
      <div class="col-md-3">
        <p class="text-center"> <%= visit.next.to_formatted_s(:long)%> </p>
      </div>
      <div class="col-md-3">
        <p> <%= link_to 'Prescription', patient_visit_path(@patient, visit), class: "center-block btn btn-primary" %> </p>
      </div>
        <div class="col-md-3">
          <p> <%= link_to 'Change Appointment', edit_patient_visit_path(@patient, visit), class: "center-block btn btn-info" %> </p>
        </div>
        <div class="col-md-3">
          <p> <%= link_to 'delete', patient_visit_path(@patient, visit), 
            method: :delete,
            data: { confirm: 'Are you sure?' },
            class: "center-block btn btn-danger" %> 
          </p>
        </div>
      </div>
    <% end %>
    <%= will_paginate @visits %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/visits/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [@patient, @visit] do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label 'Date of Apointment' %>
        <%= f.date_field :next, class: 'form-control', required: true %>

        <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/visits/edit.html.erb
<% provide(:title, 'Change Appointment') %>
<h1> Change Appointment </h1>

<%= render 'form' %>

app/views/visits/new.html.erb
<% provide(:title, 'Make an Appointment') %>
<h2>Add Next Appointment Date</h2>

<%= render 'form' %>

app/views/visits/show.html.erb
<% provide(:title, 'Appointment') %>
<h1>Appointment of <%= @patient.name %> </h1>

<div class="row">
  <div class="col-sm-9 col-md-offset-3">
    <div class="row">
      <div class="col-xs-8 col-sm-6">
        Date:
      </div>
      <div class="col-xs-4 col-sm-6">
        <%= @visit.next.to_formatted_s(:long) %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Bilal Hospital</h1>

  <h2>
    Your health is important to us
  </h2>

  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
</div>

<div class='row'>
	<div class='col-md-12'>
		<div class="center">
			<%= image_tag(("care.jpg"), class: 'care_image') %>
		</div>
	</div>
</div>